name: GitHub Actions Workflow

on:
  issues:
    types:
      - opened

jobs:
  greet_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Event Action: ${{ github.event.action }}"
      - name: Greet Issue Creator
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
        run: |
          echo "Thanks for opening this issue!"
