name: GithubBot

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - reopened

jobs:
  greet_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for creating this issue',
            });
