name: GithubBot

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - reopened

jobs:
  greet_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Commenter
        if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for creating this issue',
            });
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers to PR
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'reopened' }}
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const reviewers = ["rootxrishabh"];
            await github.pulls.requestReviewers({ owner, repo, pull_number: number, reviewers });
  check_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Stale PRs
        if: github.event_name == 'pull_request' && github.event.action == 'reopened'
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            const currentDate = new Date();
            const staleLabel = 'stale';
            const { data: pullRequests } = await github.pulls.list({
              owner,
              repo,
              state: 'open',
            });
            for (const pr of pullRequests) {
              const prDate = new Date(pr.updated_at);
              const daysSinceUpdate = Math.floor((currentDate - prDate) / (1000 * 60 * 60 * 24));
              if (1 > 0) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pr.number,
                  labels: [staleLabel],
                });
              }
            }
